apiVersion: v1
data:
  gnb_config.yml: |
    cu_cp:
      amf:
        addrs: 10.53.1.2
        port: 38412
        bind_addrs: 10.53.1.3
        supported_tracking_areas:
          - tac: 7
            plmn_list:
              - plmn: "00101"
                tai_slice_support_list:
                  - sst: 1
    metrics:
      autostart_stdout_metrics: true
      enable_json: true
    remote_control:
      bind_addr: 0.0.0.0
      enabled: true
    ru_sdr:
      device_driver: uhd
      device_args: type=b200,num_recv_frames=64,num_send_frames=64
      srate: 23.04
      otw_format: sc12
      tx_gain: 80
      rx_gain: 40
    cell_cfg:
      dl_arfcn: 632628
      band: 78
      channel_bandwidth_MHz: 20
      common_scs: 30
      plmn: "00101"
      tac: 7
      pci: 1
    log:
      filename: /tmp/gnb.log
      all_level: warning
    pcap:
      mac_enable: false
      mac_filename: /tmp/gnb_mac.pcap
      ngap_enable: false
      ngap_filename: /tmp/gnb_ngap.pcap
kind: ConfigMap
metadata:
  name: gnb_config
