apiVersion: v1
data:
  gnb_config.yml: |
    cu_cp:
      amf:
        addrs: 10.53.1.2
        port: 38412
        bind_addrs: 10.53.1.3
        supported_tracking_areas:
          - tac: 7
            plmn_list:
              - plmn: "00101"
                tai_slice_support_list:
                  - sst: 1
    metrics:
      autostart_stdout_metrics: true
      enable_json: true
    remote_control:
      bind_addr: 0.0.0.0
      enabled: true
    ru_sdr:
      device_driver: uhd
      device_args: type=b200,num_recv_frames=64,num_send_frames=64
      srate: 23.04
      otw_format: sc12
      tx_gain: 80
      rx_gain: 40
    cell_cfg:
      dl_arfcn: 632628
      band: 78
      channel_bandwidth_MHz: 20
      common_scs: 30
      plmn: "00101"
      tac: 7
      pci: 1
    log:
      filename: /tmp/gnb.log
      all_level: warning
    pcap:
      mac_enable: false
      mac_filename: /tmp/gnb_mac.pcap
      ngap_enable: false
      ngap_filename: /tmp/gnb_ngap.pcap
kind: ConfigMap
metadata:
  name: gnb-config
---
apiVersion: v1
data:
  open5gs-5gc.yml: |
    #
    # Copyright 2013-2025 Software Radio Systems Limited
    #
    # By using this file, you agree to the terms and conditions set
    # forth in the LICENSE file which can be found at the top level of
    # the distribution.
    #
    
    db_uri: mongodb:///open5gs
    
    logger:
    
    test:
      serving:
        - plmn_id:
            mcc: 001
            mnc: 01
    
    global:
      parameter:
        no_ipv6: true
        # no_nrf: true
        # no_scp: true
        no_sepp: true
        # no_amf: true
        # no_smf: true
        # no_upf: true
        # no_ausf: true
        # no_udm: true
        # no_pcf: true
        # no_nssf: true
        # no_bsf: true
        # no_udr: true
        # no_mme: true
        # no_sgwc: true
        # no_sgwu: true
        # no_pcrf: true
        # no_hss: true
    
    mme:
      freeDiameter:
        identity: mme.localdomain
        realm: localdomain
        listen_on: 127.0.0.2
        no_fwd: true
        load_extension:
          - module: "/open5gs/install/lib/x86_64-linux-gnu/freeDiameter/dbg_msg_dumps.fdx"
            conf: 0x8888
          - module: "/open5gs/install/lib/x86_64-linux-gnu/freeDiameter/dict_rfc5777.fdx"
          - module: "/open5gs/install/lib/x86_64-linux-gnu/freeDiameter/dict_mip6i.fdx"
          - module: "/open5gs/install/lib/x86_64-linux-gnu/freeDiameter/dict_nasreq.fdx"
          - module: "/open5gs/install/lib/x86_64-linux-gnu/freeDiameter/dict_nas_mipv6.fdx"
          - module: "/open5gs/install/lib/x86_64-linux-gnu/freeDiameter/dict_dcca.fdx"
          - module: "/open5gs/install/lib/x86_64-linux-gnu/freeDiameter/dict_dcca_3gpp.fdx"
        connect:
          - identity: hss.localdomain
            address: 127.0.0.8
    
      s1ap:
        server:
          - address: 
      gtpc:
        server:
          - address: 
        client:
          sgwc:
            - address: 127.0.0.3
          smf:
            - address: 127.0.0.4
      gummei:
        - plmn_id:
            mcc: 001
            mnc: 01
          mme_gid: 2
          mme_code: 1
      tai:
        - plmn_id:
            mcc: 001
            mnc: 01
          tac: 7
      security:
        integrity_order: [EIA2, EIA1, EIA0]
        ciphering_order: [EEA0, EEA1, EEA2]
      network_name:
        full: 
        short: 
      time:
        t3412:
          value: 540
    
    sgwc:
      gtpc:
        server:
          - address: 127.0.0.3
      pfcp:
        server:
          - address: 127.0.0.3
        client:
          sgwu:
            - address: 127.0.0.6
    
    smf:
      sbi:
        server:
          - address: 127.0.0.4
            port: 7777
        client:
          scp:
            - uri: http://127.0.0.22:7777
      pfcp:
        server:
          - address: 127.0.0.4
        client:
          upf:
            - address: 127.0.0.7
      gtpc:
        server:
          - address: 127.0.0.4
      gtpu:
        server:
          - address: 127.0.0.4
      metrics:
        server:
          - address: 127.0.0.4
            port: 9090
      session:
        - subnet: 10.45.0.0/24
          gateway: 10.45.0.1
    
      dns:
        - 8.8.8.8
        - 8.8.4.4
      mtu: 1400
      freeDiameter:
        identity: smf.localdomain
        realm: localdomain
        listen_on: 127.0.0.4
        no_fwd: true
        load_extension:
          - module: "/open5gs/install/lib/x86_64-linux-gnu/freeDiameter/dbg_msg_dumps.fdx"
            conf: 0x8888
          - module: "/open5gs/install/lib/x86_64-linux-gnu/freeDiameter/dict_rfc5777.fdx"
          - module: "/open5gs/install/lib/x86_64-linux-gnu/freeDiameter/dict_mip6i.fdx"
          - module: "/open5gs/install/lib/x86_64-linux-gnu/freeDiameter/dict_nasreq.fdx"
          - module: "/open5gs/install/lib/x86_64-linux-gnu/freeDiameter/dict_nas_mipv6.fdx"
          - module: "/open5gs/install/lib/x86_64-linux-gnu/freeDiameter/dict_dcca.fdx"
          - module: "/open5gs/install/lib/x86_64-linux-gnu/freeDiameter/dict_dcca_3gpp.fdx"
        connect:
          - identity: pcrf.localdomain
            address: 127.0.0.9
      security_indication:
      # Uncomment to enable UP integrity protection
      #   integrity_protection_indication: preferred
      #   confidentiality_protection_indication: preferred
    
    amf:
      sbi:
        server:
          - address: 127.0.0.5
            port: 7777
        client:
          scp:
            - uri: http://127.0.0.22:7777
      ngap:
        server:
          - address: 
      guami:
        - plmn_id:
            mcc: 001
            mnc: 01
          amf_id:
            region: 2
            set: 1
      tai:
        - plmn_id:
            mcc: 001
            mnc: 01
          tac: 7
      plmn_support:
        - plmn_id:
            mcc: 001
            mnc: 01
          s_nssai:
            - sst: 1
      security:
        integrity_order: [NIA2, NIA1, NIA0]
        ciphering_order: [NEA0, NEA1, NEA2]
      network_name:
        full: 
        short: 
      amf_name: open5gs-amf0
      time:
        t3512:
          value: 540 # 9 minutes * 60 = 540 seconds
    
    sgwu:
      pfcp:
        server:
          - address: 127.0.0.6
      gtpu:
        server:
          - address: 127.0.0.6
    
    upf:
      pfcp:
        server:
          - address: 127.0.0.7
      gtpu:
        server:
          - address: 
            advertise: 
      session:
        - subnet: 10.45.0.0/24
          gateway: 10.45.0.1
    
    hss:
      freeDiameter:
        identity: hss.localdomain
        realm: localdomain
        listen_on: 127.0.0.8
        no_fwd: true
        load_extension:
          - module: "/open5gs/install/lib/x86_64-linux-gnu/freeDiameter/dbg_msg_dumps.fdx"
            conf: 0x8888
          - module: "/open5gs/install/lib/x86_64-linux-gnu/freeDiameter/dict_rfc5777.fdx"
          - module: "/open5gs/install/lib/x86_64-linux-gnu/freeDiameter/dict_mip6i.fdx"
          - module: "/open5gs/install/lib/x86_64-linux-gnu/freeDiameter/dict_nasreq.fdx"
          - module: "/open5gs/install/lib/x86_64-linux-gnu/freeDiameter/dict_nas_mipv6.fdx"
          - module: "/open5gs/install/lib/x86_64-linux-gnu/freeDiameter/dict_dcca.fdx"
          - module: "/open5gs/install/lib/x86_64-linux-gnu/freeDiameter/dict_dcca_3gpp.fdx"
        connect:
          - identity: mme.localdomain
            address: 127.0.0.2
    pcrf:
      freeDiameter:
        identity: pcrf.localdomain
        realm: localdomain
        listen_on: 127.0.0.9
        no_fwd: true
        load_extension:
          - module: "/open5gs/install/lib/x86_64-linux-gnu/freeDiameter/dbg_msg_dumps.fdx"
            conf: 0x8888
          - module: "/open5gs/install/lib/x86_64-linux-gnu/freeDiameter/dict_rfc5777.fdx"
          - module: "/open5gs/install/lib/x86_64-linux-gnu/freeDiameter/dict_mip6i.fdx"
          - module: "/open5gs/install/lib/x86_64-linux-gnu/freeDiameter/dict_nasreq.fdx"
          - module: "/open5gs/install/lib/x86_64-linux-gnu/freeDiameter/dict_nas_mipv6.fdx"
          - module: "/open5gs/install/lib/x86_64-linux-gnu/freeDiameter/dict_dcca.fdx"
          - module: "/open5gs/install/lib/x86_64-linux-gnu/freeDiameter/dict_dcca_3gpp.fdx"
        connect:
          - identity: smf.localdomain
            address: 127.0.0.4
    
    nrf:
      sbi:
        server:
          - address: 127.0.0.10
            port: 7777
    
    scp:
      sbi:
        server:
          - address: 127.0.0.22
            port: 7777
        client:
          nrf:
            - uri: http://127.0.0.10:7777
    
    ausf:
      sbi:
        server:
          - address: 127.0.0.11
            port: 7777
        client:
          scp:
            - uri: http://127.0.0.22:7777
    
    udm:
      sbi:
        server:
          - address: 127.0.0.12
            port: 7777
        client:
          scp:
            - uri: http://127.0.0.22:7777
    
    pcf:
      sbi:
        server:
          - address: 127.0.0.13
            port: 7777
        client:
          scp:
            - uri: http://127.0.0.22:7777
      metrics:
        server:
          - address: 127.0.0.13
            port: 9090
    
    nssf:
      sbi:
        server:
          - address: 127.0.0.14
            port: 7777
        client:
          scp:
            - uri: http://127.0.0.22:7777
          nsi:
            - uri: http://127.0.0.10:7777
              s_nssai:
                sst: 1
    bsf:
      sbi:
        server:
          - address: 127.0.0.15
            port: 7777
        client:
          scp:
            - uri: http://127.0.0.22:7777
    
    udr:
      sbi:
        server:
          - address: 127.0.0.20
            port: 7777
        client:
          scp:
            - uri: http://127.0.0.22:7777
kind: ConfigMap
metadata:
  name: 5gc-config
